### ISSUE TITLE
more utilities

### ISSUE THREAD

**Issue by cpuQ** [lugosieben/utools#29]
hi again, i thought some of these features/mods could be nice to have in utools:
- auto fishing
  - configuration ideas could be: recasting delay
- auto tool switching
- [break free](https://modrinth.com/mod/breakfree)
- [inventory move](https://modrinth.com/mod/invmove)

another thing i was wondering was, will it be possible to add optimization for Light Overlay? it has a pretty significant frame drop for a few seconds when enabling it.

**Comment by lugosieben** [comment]
- [ ] auto fishing: I think it's too cheaty since you can't just use an external tool like autoclicker to repruduce
- [x] Auto Tool Switching: Great idea, will definitely add
- [x] Break Free aswell
- [x] Same for inventory move

I will go on vacation for 1.5 weeks tomorrow morning, so I doubt I will get done with all of those features today, but I'll try

**Comment by lugosieben** [comment]
@cpuQ sorry but i cant wrap my head around the auto tool switching and inventory move just wont work. I'll still try to do the inventory move tho

**Comment by cpuQ** [comment]
thats totally fine :D ty for looking into it

**Comment by lugosieben** [comment]
You can already download the version with "Break Free" here: https://github.com/lugosieben/utools/actions/runs/10289304897/artifacts/1786931628

I will upload to Modrinth / Github Releases soon aswell tho
