### ISSUE TITLE
Support for Minecraft 1.21.3

### ISSUE THREAD

**Issue by Yamato320** [lugosieben/utools#41]
An update of the Mod to the latest version of Minecraft, which is 1.21.3.

**Comment by lugosieben** [comment]
I will probably do this in the next days, but I'm busy right now, sorry

**Comment by lugosieben** [comment]
Because of lots of internal rendering changes, I won't be able to deliver and update that soon, since there is also no documentation about all changes. Sorry for letting you wait!

**Comment by lugosieben** [comment]
You can now download the early dev builds in the PR! #42

**Comment by lugosieben** [comment]
@Yamato320 you can now use every feature of UTools for 1.21.3. I'm not publishing it on Modrinth since I'm uncertain if there are any bugs. This is the download link for the 1.21.3 version: https://github.com/lugosieben/utools/actions/runs/11872454262/artifacts/2196962244 Please make issues if you encounter any bugs!

**Comment by lugosieben** [comment]
I already encountered a bug (fog not working). You can download the newest versions by [downloading artifacts](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/downloading-workflow-artifacts) of the newest ["build" action](https://github.com/lugosieben/utools/actions/workflows/build.yml)
